//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmicThinking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Algorithmic_Thinking_ModelContainer : DbContext
    {
        public Algorithmic_Thinking_ModelContainer()
            : base("name=Algorithmic_Thinking_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }

        // public System.Data.Entity.DbSet<AlgorithmicThinking.Models.Location> Locations { get; set; }
        // public System.Data.Entity.DbSet<AlgorithmicThinking.Models.Location> Locations { get; set; }
    }
}
