//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmicThinking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        [Required]
        public int Id { get; set; }
        [Required]
        [StringLength(255, MinimumLength = 4)]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
        [Required]
        public int ChapterId { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Chapter Chapter { get; set; }
    }
}
