//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorithmicThinking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int Id { get; set; }
        public string Uid { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Content { get; set; }
        public int SectionId { get; set; }
        public int CommentId { get; set; }
    }
}
